export const robots = [
  {
    id: 1,
    name: "Andrii Melnyk",
    username: "Mel",
    email: "andrii@april.biz",
    description:
      "This is the description on the robot. This robot is a great robat for you and your kids. If this robot see another robot can attack it. Don't wait until the end on it's battery, charge it on time and it will last long.",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 5000,
    },
    rate: 4.4,
    price: 399,
    active: true,
  },
  {
    id: 2,
    name: "Kyryll Melnyk",
    username: "Kir",
    email: "kyryll@melissa.tv",
    description: "This is the description on the robot",
    property: {
      speed: 90,
      power: 100,
      size: 120,
      battery: 250,
      capacity: 8000,
    },
    rate: 3.4,
    price: 399,
    active: true,
  },
  {
    id: 3,
    name: "Nikita Melnyk",
    username: "Nik",
    email: "nikita@yesenia.net",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 60,
      size: 120,
      battery: 300,
      capacity: 3000,
    },
    rate: 4.8,
    price: 399,
    active: true,
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 2.4,
    price: 399,
    active: true,
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 3.4,
    price: 399,
    active: true,
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.1,
    price: 399,
    active: true,
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 11,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 12,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 13,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 14,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 15,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 16,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 17,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 18,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 19,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 20,
    name: "Super Rose",
    username: "Rose",
    email: "Rey.rose@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 21,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 22,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 23,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 24,
    name: "Andrii Melnyk",
    username: "Mel",
    email: "andrii@april.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 25,
    name: "Kyryll Melnyk",
    username: "Kir",
    email: "kyryll@melissa.tv",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 26,
    name: "Nikita Melnyk",
    username: "Nik",
    email: "nikita@yesenia.net",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 27,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 28,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 29,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 30,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 31,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 32,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 33,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 34,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 35,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 36,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 37,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 38,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 39,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 40,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 41,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 42,
    name: "Super Rose",
    username: "Rose",
    email: "Rey.rose@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 43,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 44,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
  {
    id: 45,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    description: "This is the description on the robot",
    property: {
      speed: 75,
      power: 80,
      size: 120,
      battery: 200,
      capacity: 500,
    },
    rate: 4.5,
    price: 399,
    active: true,
  },
];
